In [ ]:
#1) Write a Python program to check whether a number is even or odd using if-else.

In [1]:
number = int(input("Enter a number: "))

if number % 2 == 0:
    print("The number is even")
else:
    print("The number is odd")

Enter a number:  15


The number is odd


In [ ]:
#2) Write a for loop that prints numbers from 10 to 1 in reverse

In [2]:
for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [ ]:
#3) Write a while loop that keeps asking the user to input a number until they enter 0.

In [3]:
num = int(input("Enter a number (0 to stop): "))
while num != 0:
    num = int(input("Enter a number (0 to stop): "))

Enter a number (0 to stop):  1
Enter a number (0 to stop):  0


In [ ]:
#3) Write a function that accepts two numbers and returns their sum.

In [4]:
def two_sum(a,b):
    return a+b
two_sum(10,25)

35

In [ ]:
#4) What will be the output of this code: print(list(map(lambda x: x*x, [1, 2, 3])))?

In [ ]:
Ans:- [1,4,9]

In [ ]:
#5) Use the filter() function to extract only even numbers from a list.

In [6]:
num=[1,2,3,4,5,6,7,8,9,10]
print(list(filter(lambda x:x%2==0,num)))

[2, 4, 6, 8, 10]


In [ ]:
#6) Purpose of the else block in a try-except-else construct:

The else block is used to write code that should run only when no exception occurs in the try block.
It helps to keep the program clean by separating normal execution from error handling.

If the code inside the try block runs successfully without any errors, the code inside the else block will be executed.
If an error happens in the try block, the except block runs and the else block will be skipped.

In [ ]:
#7) Write a try-except block to handle division by zero.

In [8]:
try:
    a = int(input("Enter numerator: "))
    b = int(input("Enter denominator: "))
    result = a / b
    print("Result:", result)
except ZeroDivisionError:
    print("You can't divide by zero.")


Enter numerator:  10
Enter denominator:  0


You can't divide by zero.


In [ ]:
#8) What is the output of this lambda function? print((lambda x, y: x+y)(5, 3))

In [9]:
print((lambda x, y: x+y)(5, 3))

8


In [ ]:
#9)Define a class named Dog with properties name and breed. Add a method bark().

In [10]:
class Dog:
    def __init__(self,name,breed):
        self.name=name
        self.breed=breed
    def bark(self):
        print(f" Dog name: {self.name} and Breed : {self.breed}")
d=Dog("Puppy","German Shepherd")
d.bark()

 Dog name: Puppy and Breed : German Shepherd


In [ ]:
#10) Create two objects of the Dog class and call their methods.

In [11]:
class Dog:
    def __init__(self,name,breed):
        self.name=name
        self.breed=breed
    def bark(self):
        print(f" Dog name: {self.name} and Breed : {self.breed}")
d=Dog("Puppy","German Shepherd")
d1=Dog("Rahu","Bulldog")
d.bark()
d1.bark()

 Dog name: Puppy and Breed : German Shepherd
 Dog name: Rahu and Breed : Bulldog


In [ ]:
#11)What is the difference between class variables and instance variables?

In [ ]:
#Class variables are the same for every object made from the class. If you change it in one place, it changes for all objects. It's like a rule or setting shared by everyone in a group.

#Instance variables are different for each object. They hold data that's specific to that one object only—like your name or age compared to someone else's

In [ ]:
#12) What will this print: print("apple" if 5 > 3 else "banana")?

In [12]:
print("apple" if 5 > 3 else "banana")

apple


In [ ]:
#13) Write a function that accepts a list and returns the list of squares using list comprehension.

In [ ]:
def get_squares(numbers):
    return [x**2 for x in numbers]

# Example
nums = [1, 2, 3, 4]
print(get_squares(nums))  # Output: [1, 4, 9, 16]


In [ ]:
#14) Explain what map() and filter() return when executed.

In [ ]:
# map() returns a map object, which is an iterator. It applies a function to each item in a list (or any iterable) and returns the results.

# filter() also returns a filter object, which is an iterator. It applies a function that returns True or False and keeps only the items where the function returns True.

# To actually see the results, you usually convert them to a list using list()

In [13]:
# Using map()
nums = [1, 2, 3]
squares = map(lambda x: x**2, nums)
print(list(squares))  # Output: [1, 4, 9]

# Using filter()
nums = [1, 2, 3, 4, 5]
even = filter(lambda x: x % 2 == 0, nums)
print(list(even))  # Output: [2, 4]

[1, 4, 9]
[2, 4]


In [ ]:
NUMPY:-

In [ ]:
#1) Create a 3x3 matrix using np.random.randint(0, 10, (3, 3)).

In [15]:
import numpy as np
n=np.random.randint(0, 10, (3, 3))
print(n)

[[0 7 7]
 [5 8 3]
 [0 5 4]]


In [ ]:
#2) Slice the above matrix to extract the first two rows.

In [16]:
first_two_rows = n[:2]
print("First Two Rows:")
print(first_two_rows)

First Two Rows:
[[0 7 7]
 [5 8 3]]


In [ ]:
#3) Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1

In [ ]:
# i Don't know need to learn

In [ ]:
#4) Perform element-wise addition, subtraction, and multiplication of two matrices

In [18]:
add = a + b
sub = a - b
mul = a * b

print("Element-wise Addition:\n", add)
print("Element-wise Subtraction:\n", sub)
print("Element-wise Multiplication:\n", mul)

Element-wise Addition:
 [[15  7  9]
 [ 8 12  5]
 [12  9  5]]
Element-wise Subtraction:
 [[ 1  3  7]
 [-4 -4  1]
 [ 4 -7  1]]
Element-wise Multiplication:
 [[56 10  8]
 [12 32  6]
 [32  8  6]]


In [ ]:
#5) Demonstrate broadcasting by adding a 1D array to a 2D array

In [19]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

broadcasted = arr_2d + arr_1d
print("Broadcasted Addition:\n", broadcasted)

Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


In [ ]:
#6) Use np.clip to limit values in a matrix to a minimum of 2 and maximum of 8

In [20]:
clipped = np.clip(a, 2, 8)
print("Clipped Matrix (min=2, max=8):\n", clipped)

Clipped Matrix (min=2, max=8):
 [[8 5 8]
 [2 4 3]
 [8 2 3]]


In [ ]:
#7) Use np.ceil on an array of floating-point numbers [1.2, 2.5, 3.8]

In [21]:
floats = np.array([1.2, 2.5, 3.8])
ceiled = np.ceil(floats)
print("Ceiling values:\n", ceiled)

Ceiling values:
 [2. 3. 4.]


In [ ]:
#8) Use np.where to replace all elements greater than 5 with 100 in a given array

In [22]:
arr = np.array([[3, 7, 1], [9, 2, 6]])
modified = np.where(arr > 5, 100, arr)
print("Replaced values > 5 with 100:\n", modified)

Replaced values > 5 with 100:
 [[  3 100   1]
 [100   2 100]]


In [ ]:
#9) Create two 2x2 matrices and compute their dot product

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

dot_product = np.dot(x, y)
print("Dot Product:\n", dot_product)

Dot Product:
 [[19 22]
 [43 50]]
